[project]
authors = ["chappie"]
entry = "main.sw"
license = "Apache-2.0"
name = "BasePool"

[dependencies]
BalancerErrors = { path = "../../../sway-utils/contracts/helpers/BalancerErrors" }
FixedPoint = { path = "../../../sway-utils/contracts/math/FixedPoint" }
InputHelpers = { path = "../../../sway-utils/contracts/helpers/InputHelpers" }

WeightedPool = { path = "../../../weighted-pool/contracts/WeightedPool" }