[project]
authors = ["Kunal"]
entry = "main.sw"
license = "Apache-2.0"
name = "LinearPool"

[dependencies]
LinearMath = {path= "../LinearMath"}
WordCodec = {path = "../../../sway-utils/contracts/helpers/WordCodec"}
FixedPoint = {path = "../../../sway-utils/contracts/math/FixedPoint"}
BaseMinimalSwapInfoPool = {path = "../../../pool-utils/contracts/BaseMinimalSwapInfoPool"}
ERC20Helper = {path = "../../../sway-utils/contracts/helpers/ERC20Helper"}
LegacyBasePool = {path = "../../../pool-utils/contracts/LegacyBasePool"}
PoolTokens = {path = "../../../vault/contracts/PoolTokens"}
TemporarilyPausable = {path = "../../../sway-utils/contracts/helpers/TemporarilyPausable"}
BalancerPoolToken = {path = "../../../pool-utils/contracts/BalancerPoolToken"}
Authentication = {path = "../../../sway-utils/contracts/helpers/Authentication"}