[project]
authors = ["shreyansh jain"]
entry = "main.sw"
license = "Apache-2.0"
name = "AuthorizerAdaptor"

[dependencies]
BalancerErrors = { path = "../../../../sway-utils/contracts/helpers/BalancerErrors"}
