[workspace]
members = [
  "./contracts/fractional-NFT-contract",
  "./contracts/test-artifacts/fractional-NFT/NFT",
  "./contracts/token-distributor-contract",
  "./contracts/test-artifacts/token-distributor/NFT",
  "./contracts/test-artifacts/token-distributor/asset",
]
