[project]
authors = ["Kunal"]
entry = "main.sw"
license = "Apache-2.0"
name = "AssetTransferHandler"

[dependencies]
BalancerErrors = { path = "../../../sway-utils/contracts/helpers/BalancerErrors" }
AssetHelpers = { path = "../AssetHelpers" }
math = { path = "../../../sway-utils/contracts/math/math" }
# UserBalance = {path = "../UserBalance"}
