[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "staking_rewards.sw"
license = "Apache-2.0"
name = "staking-rewards"

owner = { type = "Identity", value = "std::identity::Identity::Address(0x09c0b2d1a486c439a87bcba6b46a7a1a23f3897cc83a94521a96da5c23bc58db)" }
rewards_distribution = { type = "Identity", value = "std::identity::Identity::Address(0x09c0b2d1a486c439a87bcba6b46a7a1a23f3897cc83a94521a96da5c23bc58db)" }

[dependencies]
