[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "staking_rewards.sw"
license = "Apache-2.0"
name = "staking-rewards"

[constants]
owner = { type = "b256", value = "0x09c0b2d1a486c439a87bcba6b46a7a1a23f3897cc83a94521a96da5c23bc58db" }
rewards_distribution = { type = "b256", value = "0x09c0b2d1a486c439a87bcba6b46a7a1a23f3897cc83a94521a96da5c23bc58db" }

[dependencies]
