[project]
authors = ["Kunal"]
entry = "main.sw"
license = "Apache-2.0"
name = "VaultAuthorization"

[dependencies]
BalancerErrors = {path= "../../../sway-utils/contracts/helpers/BalancerErrors"}
# Authentication = {path= "../../../sway-utils/contracts/helpers/Authentication"}
# Authorizer = {path = "../Authorizer"}
