[workspace]
members = [
  "./contracts/AMM-contract",
  "./contracts/exchange-contract",
  "./contracts/test-artifacts/malicious-implementation",
  "./scripts/atomic-add-liquidity",
  "./scripts/swap-exact-input",
  "./scripts/swap-exact-output",
]

[patch.'https://github.com/fuellabs/sway']
std = { git = "https://github.com/fuellabs/sway", branch = "feat/transaction-policies" }
