[project]
authors = ["chappie"]
entry = "main.sw"
license = "Apache-2.0"
name = "BasePoolAuthorization"

[dependencies]
Authentication = { path = "../../../sway-utils/contracts/helpers/Authentication" }