[project]
authors = ["Sahil Tembhare"]
entry = "main.sw"
license = "Apache-2.0"
name = "MinimalSwapInfoPoolsBalance"

[dependencies]
BalanceAllocation = { path = "../BalanceAllocation" }
BalancerErrors = { path = "../../../../sway-utils/contracts/helpers/BalancerErrors/" }
