[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "swap-predicate"


[dependencies]
fixed_point = { git = "https://github.com/fuellabs/sway-libs", branch = "master" }