[project]
authors = ["chappie"]
entry = "main.sw"
license = "Apache-2.0"
name = "vault"

[constants]
MASK = { type = "u64", value = "1" }
# TODO For time being there is no standard for fungible token so we are keeping them as ERC20 Later will change to the standards
# currently it's dummy id when wfuel is added we will replace it
# Wraped FUEL ID
WFUEL = { type = "b256", value = "0x8900c5bec4ca97d4febf9ceb4754a60d782abbf3cd815836c1872116f203f861" }

# Sentinel value used to indicate WFUEL with wrapping/unwrapping semantics. The zero address is a good choice for
# multiple reasons: it is cheap to pass as a calldata argument, it is a known invalid token and non-contract, and
# it is an address Pools cannot register as a token.
FUEL = { type = "b256", value = "0x8900c5bec4ca97d4febf9ceb4754a60d782abbf3cd815836c1872116f203f861" }
TOKEN_NOT_REGISTERED = { type = "u64", value = "512"}
TOKENS_LENGTH_MUST_BE_2 = { type = "u64", value = "524"}
MAX_PROTOCOL_SWAP_FEE_PERCENTAGE = { type = "u64", value = "50"}
MAX_PROTOCOL_FLASH_LOAN_FEE_PERCENTAGE = { type = "u64", value = "10"}
TOKEN_ALREADY_REGISTERED = { type = "u64", value = "522"}
PAUSE_WINDOW_END_TIME = { type = "u64", value = "1"}
BUFFER_PERIOD_END_TIME = { type = "u64", value = "2"}

[dependencies]
