[project]
authors = ["Sahil Tembhare"]
entry = "main.sw"
license = "Apache-2.0"
name = "TwoTokenPoolsBalance"

[dependencies]
BalanceAllocation = { path = "../BalanceAllocation" }
BalancerErrors = { path = "../../../../sway-utils/contracts/helpers/BalancerErrors/" }
# PoolRegistry = { path = "../../PoolRegistry" }
